version: "3.7"

# MMMMMMMMMMMMMMMMMMMMMMMMMMM  NETWORKS

networks:
  docweb:
    name: docweb
    external: true
    
# MMMMMMMMMMMMMMMMMMMMMMMMMMM  SECRETS

secrets:
  ohmyform_db_password:
    external: true
  ohmyform_admin_email:
    external: true
  ohmyform_admin_username:
    external: true
  ohmyform_admin_password:
    external: true
    
  
# MMMMMMMMMMMMMMMMMMMMMMMMMMM  EXTENSION FIELDS  
  
x-docker-defautls: &docker-defaults
  restart: unless-stopped
  networks:
    - docweb
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID

# MMMMMMMMMMMMMMMMMMMMMMMMMMM  SERVICES

services:

# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM FRONTENDS

  #  db:
  #    image: postgres:10-alpine
  #    volumes:
  #      - ./pg_data:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #      POSTGRES_DB: ohmyform
  #    restart: unless-stopped
  
  nginx:
    <<: *docker-defaults
    image: nginx:alpine
    hostname: ohmyform-nginx
    container_name: ohmyform-nginx
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8585:80"
    depends_on:
      - ui
      - api
      
  ui:
    <<: *docker-defaults
    image: ohmyform/ui
    hostname: ohmyform-ui
    container_name: ohmyform-ui
    environment:
      SERVER_ENDPOINT: http://api:5000/graphql
      PORT: 5000


  api:
    <<: *docker-defaults
    image: ohmyform/api
    hostname: ohmyform-api
    container_name: ohmyform-api
    secrets:
      - ohmyform_db_password
      - ohmyform_admin_email
      - ohmyform_admin_username
      - ohmyform_admin_password
    environment:
      CREATE_ADMIN: "true"
      ADMIN_EMAIL: /run/secrets/ohmyform_admin_email
      ADMIN_USERNAME: /run/secrets/ohmyform_admin_username
      ADMIN_PASSWORD: /run/secrets/ohmyform_admin_password
      POSTGRES_USER: ${OHMYFORM_POSTGRES_USER}
      POSTGRES_PASSWORD: /run/secrets/ohmyform_db_password
      POSTGRES_DB: ${OHMYFORM_POSTGRES_DB}
      DATABASE_DRIVER: postgres
      DATABASE_SSL: "true"
      DATABASE_URL: postgresql://${OHMYFORM_POSTGRES_USER}:${OHMYFORM_POSTGRES_PASSWORD}@${OHMYFORM_POSTGRES_DB}:5432/${OHMYFORM_POSTGRES_DB}
      MAILER_URI: smtp://local.host
      REDIS_URL: redis://redis
      PORT: 5000

  
#    links:
#      - db
#    depends_on:
#      - db
      
      