version: "3.7"

# MMMMMMMMMMMMMMMMMMMMMMMMMMM  NETWORKS

networks:
  docweb:
    name: docweb
    external: true

# MMMMMMMMMMMMMMMMMMMMMMMMMMM  EXTENSION FIELDS  

x-docker-defautls: &docker-defaults
  restart: unless-stopped
  networks:
    - docweb
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID

# MMMMMMMMMMMMMMMMMMMMMMMMMMM  SERVICES

services:

# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM FRONTENDS

  nginx-proxy:
    <<: *docker-defaults
    image: jwilder/nginx-proxy
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:8080"
      - "443:4443"
    networks:
      - docweb
    environment:
      NETWORK_ACCESS: internal
      TRUST_DOWNSTREAM_PROXY: false
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/opt/docker/app_data/nginx-proxy/letsencrypt:/etc/nginx/certs"
      
  whoami:
    image: jwilder/whoami
    hostname: whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local

volumes:
  letsencrypt:
