########################### AVILABLE OPTIONS

  # OP_HTTP_PORT
  # OP_HTTPS_PORT
  # OP_TLS_KEY_FILE
  # OP_TLS_CERT_FILE
  # OP_TLS_USE_LETSENCRYPT
  # OP_TLS_DOMAIN

########################## VARIABLES REFERENCE
version: "3.7"
########################## NETWORKS

networks:
  default:
    external:
      name: bridge
  docweb:
    name: docweb
    external: true
    
########################### LOADED IN PORTAINER

# secrets:
  
########################### SECRETS REFERENCE
services: 
########################### VOLUMES

  op-connect-api:
    image: 1password/connect-api:latest
    hostname: op-connect-api
    container_name: op-connect-api
    restart: "unless-stopped"
    environment:
      TZ: "America/Los_Angeles"
      PUID: 1000
      PGID: 1000
 #     OP_BUS_PORT: 11223
 #     OP_BUS_PEERS: op-connect-sync:11223
 #     OP_SESSION: "/opt/docker/app_data/1password/1password-credentials.json"
 #     XDG_DATA_HOME: "/opt/docker/app_data/1password/data"
    ports:
      - "8080:8080"
#     - "8443:8443"
    networks:
      - docweb
    volumes:
      - "/opt/docker/app_data/1password/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "/opt/docker/app_data/1password/data:/home/opuser/.op/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-connect-sync:
    image: 1password/connect-sync:latest
    hostname: op-connect-sync
    container_name: op-connect-sync
    restart: "unless-stopped"
    environment:
      TZ: "America/Los_Angeles"
      PUID: 1000
      PGID: 1000
#      OP_BUS_PORT: 11223
#      OP_BUS_PEERS: op-connect-api:11223
#      OP_SESSION: "/opt/docker/app_data/1password/1password-credentials.json"
#      XDG_DATA_HOME: "/opt/docker/app_data/1password/data"
    networks:
      - docweb
    ports:
      - "8081:8080"
    volumes:
      - "/opt/docker/app_data/1password//1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "/opt/docker/app_data/1password/data:/home/opuser/.op/data"
    extra_hosts:
    - "host.docker.internal:host-gateway"

volumes:
  data:
